### ISSUE TITLE
address sanitizer error in CRAN tests

### ISSUE THREAD

**Issue by jackwasey** [jackwasey/icd#128]
As usual, impossible to reproduce because of minimal information about the CRAN ASAN test environment.

This gives minimal example of how this sanitizer error is triggered:
https://github.com/google/sanitizers/wiki/AddressSanitizerExampleUseAfterScope

Of note, the clang sanitizer doesn't trigger this error, just GCC 7.1. 7.2 is the current GCC version, which alone may be the reason why I can't reproduce it (CRAN has buggy GCC version).

```
==31710==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f79ee6bc550 at pc 0x7f79f37f1b61 bp 0x7f79ee6bc300 sp 0x7f79ee6bc2f0
  WRITE of size 4 at 0x7f79ee6bc550 thread T1
  ==31710==AddressSanitizer: while reporting a bug found another one. Ignoring.
      #0 0x7f79f37f1b60 in lookupComorbidByChunkFor(std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, unsigned long, unsigned long, std::vector<int, std::allocator<int> >&) [clone ._omp_fn.0] /data/gannet/ripley/R/packages/tests-gcc-SAN/icd/src/comorbidCommon.cpp:75
      #1 0x7f7a02deed3d  (/lib64/libgomp.so.1+0x16d3d)
      #2 0x7f7a01ea136c in start_thread (/lib64/libpthread.so.0+0x736c)
      #3 0x7f7a01bd9bbe in __GI___clone (/lib64/libc.so.6+0x110bbe)
  
  Address 0x7f79ee6bc550 is located in stack of thread T1 at offset 288 in frame
      #0 0x7f79f37efadf in lookupComorbidByChunkFor(std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > > const&, unsigned long, unsigned long, std::vector<int, std::allocator<int> >&) [clone ._omp_fn.0] /data/gannet/ripley/R/packages/tests-gcc-SAN/icd/src/comorbidCommon.cpp:46
  
    This frame has 37 object(s):
      [32, 33) '<unknown>'
      [96, 97) '<unknown>'
      [160, 161) '<unknown>'
      [224, 225) '<unknown>'
      [288, 292) '<unknown>' <== Memory access at offset 288 is inside this variable
      [352, 360) 'vis_i'
      [416, 424) 'chunk_end_i'
```
etc

Full logs and traces in: https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-ASAN/icd/00check.log

**Comment by jackwasey** [comment]
Closing because I am able to trigger the sanitizer error with test code, but not the real code, thus a CRAN false positive perhaps due to older version of GCC.
